import '@fortawesome/fontawesome-free/css/all.min.css';
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/common/header/Header";
import "./globals.css";
import { UserProvider } from "./User/page"; // ✅ Import UserProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  console.log(children); 

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider> {/* ✅ Bọc app trong UserProvider */}
          <Header />
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
