import "@fortawesome/fontawesome-free/css/all.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "../components/common/footer/Footer";
import Header from "../components/common/header/Header";
import "./globals.css";
import { UserProvider } from "./User/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookingHotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
