import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "./User/page"; // ✅ Import UserProvider
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  console.log(children); // Debugging để kiểm tra children

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider> {/* ✅ Bọc app trong UserProvider */}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
