-- Script để thêm các bài viết mẫu về du lịch vào bảng posts

USE bookinghotel;

-- Xóa dữ liệu cũ nếu cần (tùy chọn, comment nếu không muốn xóa)
-- DELETE FROM posts;

-- Thêm các bài viết mẫu về du lịch
INSERT INTO posts (title, content, image, category, created_at) VALUES
(
  '10 Địa Điểm Du Lịch Đẹp Nhất Việt Nam Năm 2024',
  'Việt Nam là một đất nước với vẻ đẹp thiên nhiên tuyệt vời và nền văn hóa đa dạng. Từ những bãi biển tuyệt đẹp ở miền Trung đến những ngọn núi hùng vĩ ở phía Bắc, Việt Nam có rất nhiều điểm đến hấp dẫn cho du khách. Dưới đây là 10 địa điểm du lịch đẹp nhất mà bạn không nên bỏ lỡ:\n\n1. Vịnh Hạ Long - Quảng Ninh\nVịnh Hạ Long là một trong những kỳ quan thiên nhiên của thế giới với hàng nghìn đảo đá vôi kỳ vĩ. Du khách có thể tham gia các tour du thuyền để khám phá các hang động và tận hưởng cảnh quan tuyệt đẹp.\n\n2. Phố Cổ Hội An - Quảng Nam\nHội An là một thị trấn cổ được UNESCO công nhận là Di sản Văn hóa Thế giới. Với kiến trúc cổ kính, những chiếc đèn lồng đầy màu sắc và ẩm thực đặc sắc, Hội An là điểm đến lý tưởng cho những ai yêu thích văn hóa và lịch sử.\n\n3. Sapa - Lào Cai\nSapa nổi tiếng với những ruộng bậc thang xanh mướt và khí hậu mát mẻ quanh năm. Đây là nơi lý tưởng để trekking và tìm hiểu văn hóa của các dân tộc thiểu số.\n\n4. Đà Lạt - Lâm Đồng\nĐà Lạt được mệnh danh là "thành phố ngàn hoa" với khí hậu mát mẻ và cảnh quan thiên nhiên tuyệt đẹp. Du khách có thể tham quan các vườn hoa, hồ nước và các công trình kiến trúc Pháp cổ.\n\n5. Nha Trang - Khánh Hòa\nNha Trang là một trong những bãi biển đẹp nhất Việt Nam với nước biển trong xanh và bãi cát trắng mịn. Thành phố này cũng có nhiều điểm tham quan như Vinpearl Land và các đảo xung quanh.\n\n6. Phú Quốc - Kiên Giang\nPhú Quốc là hòn đảo lớn nhất Việt Nam với những bãi biển hoang sơ và hệ sinh thái biển phong phú. Đây là điểm đến lý tưởng cho những ai muốn nghỉ dưỡng và thư giãn.\n\n7. Mù Cang Chải - Yên Bái\nMù Cang Chải nổi tiếng với những ruộng bậc thang vàng óng vào mùa lúa chín. Cảnh quan nơi đây sẽ khiến bạn phải trầm trồ trước vẻ đẹp của thiên nhiên.\n\n8. Cố Đô Huế - Thừa Thiên Huế\nHuế là cố đô của Việt Nam với nhiều di tích lịch sử và văn hóa. Du khách có thể tham quan Đại Nội, các lăng tẩm và thưởng thức ẩm thực cung đình.\n\n9. Mũi Né - Bình Thuận\nMũi Né là điểm đến nổi tiếng với những cồn cát đỏ và vàng, tạo nên cảnh quan độc đáo. Đây cũng là nơi lý tưởng cho các hoạt động thể thao biển.\n\n10. Cát Bà - Hải Phòng\nCát Bà là hòn đảo lớn nhất trong quần đảo Cát Bà với hệ sinh thái rừng và biển phong phú. Đây là điểm đến lý tưởng cho những ai yêu thích thiên nhiên và các hoạt động ngoài trời.',
  NULL,
  'Du lịch',
  NOW()
),
(
  'Kinh Nghiệm Đặt Phòng Khách Sạn Online Hiệu Quả',
  'Đặt phòng khách sạn online đã trở thành cách phổ biến nhất để tìm và đặt chỗ nghỉ khi đi du lịch. Tuy nhiên, để có được trải nghiệm tốt nhất và tiết kiệm chi phí, bạn cần biết một số mẹo và kinh nghiệm sau:\n\n1. So sánh giá trên nhiều trang web\nKhông nên chỉ đặt trên một trang web duy nhất. Hãy so sánh giá trên nhiều trang như Booking.com, Agoda, Expedia, và các trang web đặt phòng khách sạn trực tiếp. Mỗi trang có thể có mức giá và chương trình khuyến mãi khác nhau.\n\n2. Đặt phòng sớm\nĐặt phòng sớm thường giúp bạn có được mức giá tốt hơn, đặc biệt là trong mùa cao điểm. Nhiều khách sạn cũng có chương trình giảm giá cho khách đặt sớm.\n\n3. Kiểm tra chính sách hủy phòng\nTrước khi đặt, hãy đọc kỹ chính sách hủy phòng. Một số phòng có thể được hủy miễn phí đến một ngày trước khi nhận phòng, trong khi một số khác có thể không được hoàn tiền.\n\n4. Đọc đánh giá của khách hàng\nĐánh giá của khách hàng là nguồn thông tin quan trọng để đánh giá chất lượng khách sạn. Hãy đọc cả đánh giá tích cực và tiêu cực để có cái nhìn toàn diện.\n\n5. Kiểm tra vị trí khách sạn\nVị trí là yếu tố quan trọng khi chọn khách sạn. Hãy kiểm tra xem khách sạn có gần các điểm tham quan, nhà hàng và phương tiện giao thông công cộng không.\n\n6. Tận dụng chương trình khách hàng thân thiết\nNhiều trang web đặt phòng có chương trình khách hàng thân thiết với các ưu đãi như tích điểm, giảm giá và nâng cấp phòng miễn phí.\n\n7. Đặt phòng linh hoạt\nNếu có thể, hãy chọn các ngày linh hoạt. Giá phòng có thể thay đổi đáng kể tùy thuộc vào ngày trong tuần và mùa.\n\n8. Kiểm tra các khoản phí ẩn\nMột số khách sạn có thể tính thêm các khoản phí như phí dịch vụ, phí resort, hoặc phí đỗ xe. Hãy kiểm tra kỹ trước khi đặt.\n\n9. Liên hệ trực tiếp với khách sạn\nĐôi khi, đặt phòng trực tiếp với khách sạn có thể mang lại mức giá tốt hơn hoặc các ưu đãi đặc biệt mà các trang web đặt phòng không có.\n\n10. Sử dụng ứng dụng di động\nNhiều trang web đặt phòng có ứng dụng di động với các ưu đãi độc quyền và thông báo về các deal tốt.',
  NULL,
  'Khách sạn',
  NOW()
),
(
  'Ẩm Thực Việt Nam: Những Món Ăn Không Thể Bỏ Lỡ',
  'Ẩm thực Việt Nam là một trong những nền ẩm thực đa dạng và phong phú nhất thế giới. Với sự kết hợp tinh tế giữa các nguyên liệu tươi ngon và gia vị đặc trưng, mỗi món ăn Việt Nam đều mang đến một trải nghiệm độc đáo. Dưới đây là những món ăn bạn nhất định phải thử khi đến Việt Nam:\n\n1. Phở\nPhở là món ăn quốc hồn quốc túy của Việt Nam. Một bát phở nóng hổi với nước dùng trong veo, thịt bò hoặc gà mềm, cùng với rau thơm và chanh sẽ làm ấm lòng bạn vào bất kỳ thời điểm nào trong ngày.\n\n2. Bánh Mì\nBánh mì Việt Nam là sự kết hợp hoàn hảo giữa ẩm thực Pháp và Việt Nam. Với lớp vỏ giòn rụm bên ngoài và nhân đa dạng bên trong, bánh mì là món ăn đường phố phổ biến nhất.\n\n3. Bún Chả\nBún chả Hà Nội là món ăn đặc trưng của thủ đô với thịt nướng thơm lừng, bún tươi và nước mắm pha chua ngọt đậm đà.\n\n4. Gỏi Cuốn\nGỏi cuốn là món ăn thanh mát với tôm, thịt, rau sống và bún được cuốn trong lớp bánh tráng trong suốt, thường được chấm với nước mắm pha.\n\n5. Cơm Tấm\nCơm tấm là món ăn đặc trưng của miền Nam với cơm gạo tấm, sườn nướng, chả trứng và đồ chua.\n\n6. Bánh Xèo\nBánh xèo là loại bánh giòn với nhân tôm, thịt và giá đỗ, thường được cuốn với rau sống và chấm nước mắm.\n\n7. Cao Lầu\nCao lầu là món mì đặc trưng của Hội An với sợi mì vàng, thịt heo, rau sống và nước dùng đậm đà.\n\n8. Bún Bò Huế\nBún bò Huế là món ăn cay nồng đặc trưng của cố đô với nước dùng đậm đà, thịt bò và chả cua.\n\n9. Chè\nChè là món tráng miệng phổ biến của Việt Nam với nhiều loại khác nhau như chè đậu xanh, chè thái, chè ba màu...\n\n10. Cà Phê Sữa Đá\nCà phê sữa đá là thức uống đặc trưng của Việt Nam với hương vị đậm đà và cách pha chế độc đáo.',
  NULL,
  'Ẩm thực',
  NOW()
),
(
  'Những Lưu Ý Quan Trọng Khi Đi Du Lịch Nước Ngoài',
  'Du lịch nước ngoài là một trải nghiệm tuyệt vời, nhưng cũng đòi hỏi sự chuẩn bị kỹ lưỡng để đảm bảo chuyến đi an toàn và suôn sẻ. Dưới đây là những lưu ý quan trọng mà bạn nên biết:\n\n1. Chuẩn bị giấy tờ cần thiết\nHãy đảm bảo bạn có đầy đủ các giấy tờ như hộ chiếu còn hạn, visa (nếu cần), vé máy bay, bảo hiểm du lịch và các giấy tờ quan trọng khác. Nên photo và lưu bản sao ở nhiều nơi khác nhau.\n\n2. Nghiên cứu về điểm đến\nTrước khi đi, hãy tìm hiểu về văn hóa, phong tục, luật pháp và các quy định của đất nước bạn sẽ đến. Điều này sẽ giúp bạn tránh những tình huống khó xử và thể hiện sự tôn trọng với người dân địa phương.\n\n3. Đăng ký thông tin với đại sứ quán\nHãy đăng ký thông tin chuyến đi của bạn với đại sứ quán Việt Nam tại quốc gia bạn sẽ đến. Điều này sẽ giúp bạn nhận được hỗ trợ trong trường hợp khẩn cấp.\n\n4. Mua bảo hiểm du lịch\nBảo hiểm du lịch là điều cần thiết để bảo vệ bạn khỏi các chi phí y tế và các rủi ro khác khi đi du lịch nước ngoài.\n\n5. Chuẩn bị tiền và thẻ\nHãy mang theo một số tiền mặt và thẻ tín dụng/quốc tế. Nên thông báo cho ngân hàng về chuyến đi của bạn để tránh bị khóa thẻ.\n\n6. Chuẩn bị thuốc và đồ dùng y tế\nNếu bạn đang dùng thuốc, hãy mang đủ lượng thuốc cho cả chuyến đi. Cũng nên mang theo một số thuốc cơ bản như thuốc cảm, thuốc đau bụng...\n\n7. Tải ứng dụng hữu ích\nCó nhiều ứng dụng hữu ích cho du lịch như Google Maps, Google Translate, ứng dụng đặt phòng, ứng dụng gọi xe... Hãy tải trước khi đi.\n\n8. Giữ liên lạc\nHãy cung cấp lịch trình chi tiết cho gia đình hoặc bạn bè. Cũng nên có cách giữ liên lạc như mua SIM card địa phương hoặc sử dụng WiFi.\n\n9. Cẩn thận với đồ đạc\nHãy cẩn thận với hành lý và đồ đạc cá nhân. Nên sử dụng khóa an toàn và không để đồ đạc quý giá ở nơi dễ nhìn thấy.\n\n10. Tôn trọng văn hóa địa phương\nHãy tôn trọng văn hóa, phong tục và tín ngưỡng của đất nước bạn đến thăm. Điều này không chỉ thể hiện sự tôn trọng mà còn giúp bạn có trải nghiệm tốt hơn.',
  NULL,
  'Du lịch',
  NOW()
),
(
  'Top 5 Khách Sạn Sang Trọng Tại Việt Nam',
  'Việt Nam không chỉ nổi tiếng với cảnh quan thiên nhiên tuyệt đẹp mà còn có nhiều khách sạn sang trọng đẳng cấp thế giới. Dưới đây là top 5 khách sạn sang trọng nhất tại Việt Nam:\n\n1. InterContinental Danang Sun Peninsula Resort\nNằm trên bán đảo Sơn Trà, khách sạn này mang đến trải nghiệm nghỉ dưỡng đẳng cấp với kiến trúc độc đáo và dịch vụ 5 sao. Mỗi villa đều có hồ bơi riêng và tầm nhìn ra biển tuyệt đẹp.\n\n2. The Reverie Saigon\nTọa lạc tại trung tâm thành phố Hồ Chí Minh, The Reverie Saigon là biểu tượng của sự sang trọng với thiết kế nội thất tinh xảo và dịch vụ đẳng cấp quốc tế.\n\n3. Six Senses Ninh Van Bay\nNằm tại một vịnh biển riêng tư, Six Senses Ninh Van Bay mang đến trải nghiệm nghỉ dưỡng độc đáo với các villa trên núi, trên biển và trên bãi cát.\n\n4. JW Marriott Phu Quoc Emerald Bay\nKhách sạn này được thiết kế bởi kiến trúc sư nổi tiếng Bill Bensley với chủ đề "trường học ma" độc đáo. Mỗi phòng đều được trang trí theo phong cách riêng biệt.\n\n5. Sofitel Legend Metropole Hanoi\nLà một trong những khách sạn lịch sử nhất Việt Nam, Metropole Hanoi kết hợp giữa vẻ đẹp cổ điển và tiện nghi hiện đại, mang đến trải nghiệm độc đáo cho du khách.',
  NULL,
  'Khách sạn',
  NOW()
);

-- Kiểm tra dữ liệu đã được thêm
SELECT COUNT(*) as total_posts FROM posts;
SELECT * FROM posts ORDER BY created_at DESC;

